[discord]
    enabled = false
    token = "example token"
    [discord.weekly]
        enabled = false
        day_of_week = 7
        hour_of_day = 0
        channel_id = 0
        give_reward = false
        rewards = [
            "lpv user $username parent addtemp vip 7d"
        ]
        [discord.weekly.server_announcement]
            enabled = false
            content = [
                "<bold><gradient:#F09D00:#F8BD04><st>                    </st></gradient></bold>",
                " <gradient:#F2E205:#F2A30F>OnlineTime</gradient> ",
                "<bold><gradient:#F8BD04:#F09D00><st>                    </st></gradient></bold>",
                "$prefix<bold><color:#F2E205>player Won weekly playtime reward!"
            ]
    [discord.daily]
        enabled = false
        append_gamemodes = true
        channel_id = 0